name: Build & Deploy to Render

on:
  push:
    branches:
      - main
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      SPRING_PROFILES_ACTIVE: ${{ github.ref == 'refs/heads/main' && 'main' || 'development' }}

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Java
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Build project
      - name: Build Spring Boot jar
        run: mvn clean package -DskipTests

      # 4. Deploy to Render
      - name: Deploy to Render
        uses: render-examples/deploy-action@v1
        with:
          apiKey: ${{ secrets.RENDER_API_KEY }}
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          artifact: target/*.jar
